pipeline {
   agent any

   stages {
      stage('Image Build') {
         steps {
            echo 'Infrastructure Provisioned'
            sleep 10
         }
      }
    stage('Infrastructure Provisioning') {
         steps {
            echo 'VM provisioned'
            sleep 10
         }
      }
    stage('Configure Web Server') {
         steps {
         ansibleTower(
             credential: 'root', 
             inventory: 'IaC', 
             jobTemplate: 'Configure Webserver', 
             jobType: 'run', 
             throwExceptionWhenFail: true, 
             towerCredentialsId: 'toweradmin', 
             towerLogLevel: 'full',
             importTowerLogs: true,
             removeColor: false,
             towerServer: 'tower',         
             extraVars: '''---
             rhsm_username: "mbernacc1@redhat.com"
             rhsm_password: "chanegme"
             rhsm_poolid: "8a85f98260c27fc50160c32cc5fe5ceb"'''
         )
         }
      }
   }
}
