---
- hosts: webservers
  remote_user: root
  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: motd
    copy:
      content: "Update"
      dest: /etc/motd


