---
- hosts: webservers
  remote_user: root
  tasks:
   - name: Disable all repositories except rhel-8-for-x86_64-baseos-rpms
     rhsm_repository:
       name: rhel-8-for-x86_64-baseos-rpms
       purge: True
   - name: install httpd 
     yum:
       name: httpd
       state: present
   - name: enable service httpd
     service:
       name: httpd
       enabled: yes
       state: started
   - net_banner:
    banner: login
    text: |
      this is my login banner
      that contains a multiline
      string
    state: present

