---
- hosts: webservers
  remote_user: root
  tasks:
  - name: install httpd 
    yum:
       name: httpd
       state: present
  - name: enable service httpd
    service:
       name: httpd
       enabled: yes
       state: started
  - name: message to html
    copy:
      content: "{{ msg }}"
      dest: /var/www/html/index.html
