---
- hosts: webservers
  remote_user: root
  tasks:
   - name: registration to RHSM
     community.general.redhat_subscription:
       state: present
       username: mbernacc1@redhat.com
       password: changeme
       auto_attach: true
   - name: Disable all repositories except rhel-7-server-rpms
     community.general.rhsm_repository:
       name: rhel-7-server-rpms
       purge: True
   - name: install httpd 
     yum:
       name: httpd
       state: present
   - name: enable service httpd
     service:
       name: httpd
       enabled: yes
       state: started
