---
- hosts: webservers
  remote_user: root
  tasks:
   - name: install httpd 
     yum:
       name: httpd
       state: present
   - name: enable service httpd
     service:
       name: httpd
       enabled: yes
       state: started
   - name: motd
     net_banner:
       banner: login
       text: "{{ instance_motd }}"
       state: present

